<?php
/**
 * TL_ROOT/system/modules/tags_articles/languages/de/modules.php 
 * 
 * TYPOlight extension: tags_articles 1.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloudcontent']['0'] = "Tag Cloud (Inhaltselemente)";
$GLOBALS['TL_LANG']['FMD']['tagcloudcontent']['1'] = "Dieses Modul erstellt eine Tag Cloud für Inhaltselemente in einem Contao Unterbereich.";
 
?>
