<?php
/**
 * TL_ROOT/system/modules/tags_articles/languages/de/tl_module.php 
 * 
 * TYPOlight extension: tags_articles 1.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_content_pages']['0'] = "Seiten";
$GLOBALS['TL_LANG']['tl_module']['tag_content_pages']['1'] = "Bitte wählen Sie die Seite aus, deren Inhaltselemente zur Erstellung der Tag Cloud verwendet werden sollen. Wenn die Seite Unterseiten besitzt, so werden diese Inhaltselemente ebenfalls für die Generierung der Tag Cloud verwendet.";
 
?>
